version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '54320:5432'
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

  server:
    build:
      context: ./
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      APP_DATABASE_NAME: docker
      APP_DATABASE_USER: docker
      APP_DATABASE_PWD: docker
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PORT: 5432
      APP_DATABASE_TYPE: postgres
      APP_DATABASE_SYNCHRONIZE: false
