apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  selector:
    matchLabels:
      app: database-postgres
  serviceName: database-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: database-postgres
    spec:
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: database-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /local/database
          resources:
            requests:
              memory: "32Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: database-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  # Nome do secret
                  name: database-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fair-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fair-api
  template:
    metadata:
      labels:
        app: fair-api
    spec:
      initContainers:
        - name: fair-api-migration
          image: koj3/fair-api:1.0
          command: ["npm", "run", "migration:run:local"]
          envFrom:
            - configMapRef:
                name: fair-api-configmap
          env:
            - name: APP_DATABASE_PWD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-secret
        - name: fair-api-seed
          image: koj3/fair-api:1.0
          command: ["npm", "run", "seed:local"]
          envFrom:
            - configMapRef:
                name: fair-api-configmap
          env:
            - name: APP_DATABASE_PWD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-secret
      containers:
        - name: fair-api
          image: koj3/fair-api:1.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 433
              name: https
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 3
            failureThreshold: 3
            initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: fair-api-configmap
          env:
            - name: APP_DATABASE_PWD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-secret
